import { ScenarioDefinition, ScenarioId } from '../types/scenario';
import { SurroundingActor } from '../types/obstacle';
import { Pothole, RoadSegment } from '../types/road';

export const SCENARIO_DEFINITIONS: Record<ScenarioId, ScenarioDefinition> = {
  UNMARKED_NARROW_ROAD: {
    id: 'UNMARKED_NARROW_ROAD',
    name: 'Unmarked Narrow Rural Road',
    tagline: 'Missing lane paint, unpaved irregular shoulders, parked tempo & potholes',
    description:
      'Single-carriageway rural highway with zero visible lane markings, broken asphalt edges, parked breakdown tempo, and a central pothole cluster.',
    difficulty: 'MEDIUM',
    defaultSpeedKmh: 35,
    roadWidth: 5.8,
    laneConfidence: 0.1,
    expectedBehavior:
      'Analyze drivable space corridor, detect pothole and parked vehicle, decelerate cautiously, execute smooth left evasive pass, and maintain safe clearance.',
    seed: 101,
    initialActors: [
      {
        id: 'parked_tempo',
        type: 'STATIC_OBSTACLE',
        x: 1.6,
        y: 45.0,
        speed: 0,
        vx: 0,
        vy: 0,
        heading: 0,
        acceleration: 0,
        width: 2.0,
        length: 4.8,
        behavior: 'STATIC',
        uncertainty: 0.05,
      },
      {
        id: 'rural_pedestrian',
        type: 'PEDESTRIAN',
        x: 2.3,
        y: 60.0,
        speed: 1.2,
        vx: 0.0,
        vy: 1.2,
        heading: 0,
        acceleration: 0,
        width: 0.6,
        length: 0.6,
        behavior: 'SLOW_MOVING',
        uncertainty: 0.35,
      },
      {
        id: 'oncoming_bike',
        type: 'MOTORCYCLE',
        x: -1.7,
        y: 110.0,
        speed: 9.0,
        vx: 0,
        vy: -9.0,
        heading: Math.PI,
        acceleration: 0,
        width: 0.8,
        length: 2.0,
        behavior: 'LANE_KEEPING',
        uncertainty: 0.3,
      },
    ],
    initialPotholes: [
      { id: 'pothole_1', x: 0.3, y: 28.0, diameter: 1.3, depth: 14, severity: 'SEVERE' },
      { id: 'pothole_2', x: 1.2, y: 32.0, diameter: 1.1, depth: 9, severity: 'MODERATE' },
    ],
    roadSegments: [
      {
        yStart: 0,
        yEnd: 400,
        width: 5.8,
        leftEdgeOffset: 2.9,
        rightEdgeOffset: 2.9,
        hasCenterLine: false,
        laneConfidence: 0.1,
        surfaceCondition: 'POTHOLED',
      },
    ],
  },

  UNSIGNALIZED_JUNCTION: {
    id: 'UNSIGNALIZED_JUNCTION',
    name: 'Unsignalized Urban Junction',
    tagline: 'Multi-direction crossing vehicles, non-yielding auto-rickshaws & two-wheelers',
    description:
      'Challenging Indian 4-way intersection without traffic lights. Crossing motorcycle and turning auto cut across ego path.',
    difficulty: 'HARD',
    defaultSpeedKmh: 40,
    roadWidth: 7.6,
    laneConfidence: 0.35,
    expectedBehavior:
      'Predict cross-traffic trajectory, calculate low TTC, ramp risk score to HIGH, decelerate/yield until conflict path clears, then resume navigation.',
    seed: 202,
    initialActors: [
      {
        id: 'crossing_bike',
        type: 'MOTORCYCLE',
        x: -12.0,
        y: 42.0,
        speed: 6.5,
        vx: 6.5,
        vy: 0.2,
        heading: Math.PI / 2,
        acceleration: 0,
        width: 0.8,
        length: 2.0,
        behavior: 'CROSSING',
        uncertainty: 0.45,
        targetX: 10.0,
      },
      {
        id: 'turning_auto',
        type: 'AUTO_RICKSHAW',
        x: 8.5,
        y: 54.0,
        speed: 5.0,
        vx: -4.0,
        vy: 1.5,
        heading: -Math.PI / 2.5,
        acceleration: 0,
        width: 1.3,
        length: 2.8,
        behavior: 'CROSSING',
        uncertainty: 0.4,
        targetX: -1.5,
      },
      {
        id: 'junction_pedestrian',
        type: 'PEDESTRIAN',
        x: 4.2,
        y: 65.0,
        speed: 1.3,
        vx: -1.1,
        vy: 0.2,
        heading: -Math.PI / 2,
        acceleration: 0,
        width: 0.6,
        length: 0.6,
        behavior: 'CROSSING',
        uncertainty: 0.5,
        targetX: -4.0,
      },
    ],
    initialPotholes: [
      { id: 'pothole_junc', x: -0.5, y: 35.0, diameter: 0.9, depth: 7, severity: 'MILD' },
    ],
    roadSegments: [
      {
        yStart: 0,
        yEnd: 400,
        width: 7.6,
        leftEdgeOffset: 3.8,
        rightEdgeOffset: 3.8,
        hasCenterLine: true,
        laneConfidence: 0.35,
        surfaceCondition: 'DRY_ASPHALT',
      },
    ],
  },

  HIGHWAY_SLOW_VEHICLE: {
    id: 'HIGHWAY_SLOW_VEHICLE',
    name: 'Highway + Slow Vehicle Overtake',
    tagline: 'High-speed cruising with slow-moving agricultural tractor/overloaded truck',
    description:
      'National highway scenario with ego cruising at 60 km/h encountering an overloaded sugar cane tractor crawling at 14 km/h.',
    difficulty: 'MEDIUM',
    defaultSpeedKmh: 60,
    roadWidth: 8.5,
    laneConfidence: 0.75,
    expectedBehavior:
      'Detect slow-moving vehicle ahead, forecast closing distance, evaluate safe overtake in LEFT corridor, execute smooth overtaking trajectory, and return to cruise.',
    seed: 303,
    initialActors: [
      {
        id: 'slow_tractor',
        type: 'TRUCK',
        x: 1.8,
        y: 50.0,
        speed: 3.8,
        vx: 0,
        vy: 3.8,
        heading: 0,
        acceleration: 0,
        width: 2.6,
        length: 8.0,
        behavior: 'SLOW_MOVING',
        uncertainty: 0.1,
      },
      {
        id: 'following_bike',
        type: 'MOTORCYCLE',
        x: 2.4,
        y: 25.0,
        speed: 6.0,
        vx: 0.2,
        vy: 6.0,
        heading: 0,
        acceleration: 0,
        width: 0.8,
        length: 2.0,
        behavior: 'LANE_KEEPING',
        uncertainty: 0.3,
      },
      {
        id: 'left_lane_car',
        type: 'CAR',
        x: -2.0,
        y: 110.0,
        speed: 16.0,
        vx: 0,
        vy: 16.0,
        heading: 0,
        acceleration: 0,
        width: 1.8,
        length: 4.5,
        behavior: 'LANE_KEEPING',
        uncertainty: 0.15,
      },
    ],
    initialPotholes: [],
    roadSegments: [
      {
        yStart: 0,
        yEnd: 500,
        width: 8.5,
        leftEdgeOffset: 4.25,
        rightEdgeOffset: 4.25,
        hasCenterLine: true,
        laneConfidence: 0.75,
        surfaceCondition: 'DRY_ASPHALT',
      },
    ],
  },

  DENSE_MARKET: {
    id: 'DENSE_MARKET',
    name: 'Dense Market / Chowk Navigation',
    tagline: 'High-density chaotic traffic: auto-rickshaws, bikes, pushcart vendor & pedestrians',
    description:
      'Ultra-dense commercial market street with encroaching stalls, pushcarts, and erratic two-wheelers weaving unpredictably.',
    difficulty: 'HARD',
    defaultSpeedKmh: 28,
    roadWidth: 6.8,
    laneConfidence: 0.05,
    expectedBehavior:
      'Maintain cautious speed, continuous replanning under high uncertainty envelopes, filter through narrow safe pockets without sudden jerky maneuvers.',
    seed: 404,
    initialActors: [
      {
        id: 'pushcart_vendor',
        type: 'STATIC_OBSTACLE',
        x: 2.3,
        y: 36.0,
        speed: 0.5,
        vx: 0,
        vy: 0.5,
        heading: 0,
        acceleration: 0,
        width: 1.5,
        length: 2.2,
        behavior: 'SLOW_MOVING',
        uncertainty: 0.2,
      },
      {
        id: 'weaving_rickshaw',
        type: 'AUTO_RICKSHAW',
        x: -0.8,
        y: 28.0,
        speed: 6.0,
        vx: 0,
        vy: 6.0,
        heading: 0,
        acceleration: 0,
        width: 1.3,
        length: 2.8,
        behavior: 'ERRATIC_WEAVING',
        uncertainty: 0.5,
      },
      {
        id: 'market_bike_1',
        type: 'MOTORCYCLE',
        x: 1.1,
        y: 20.0,
        speed: 7.5,
        vx: 0,
        vy: 7.5,
        heading: 0,
        acceleration: 0,
        width: 0.8,
        length: 2.0,
        behavior: 'ERRATIC_WEAVING',
        uncertainty: 0.55,
      },
      {
        id: 'shopper_1',
        type: 'PEDESTRIAN',
        x: -2.4,
        y: 45.0,
        speed: 1.1,
        vx: 0.9,
        vy: 0.1,
        heading: Math.PI / 2,
        acceleration: 0,
        width: 0.6,
        length: 0.6,
        behavior: 'CROSSING',
        uncertainty: 0.5,
        targetX: 1.0,
      },
      {
        id: 'shopper_2',
        type: 'PEDESTRIAN',
        x: 2.6,
        y: 58.0,
        speed: 1.0,
        vx: -0.8,
        vy: 0.0,
        heading: -Math.PI / 2,
        acceleration: 0,
        width: 0.6,
        length: 0.6,
        behavior: 'CROSSING',
        uncertainty: 0.5,
        targetX: -1.0,
      },
    ],
    initialPotholes: [
      { id: 'mkt_pothole_1', x: -1.2, y: 22.0, diameter: 1.0, depth: 8, severity: 'MODERATE' },
      { id: 'mkt_pothole_2', x: 0.8, y: 50.0, diameter: 1.2, depth: 11, severity: 'SEVERE' },
    ],
    roadSegments: [
      {
        yStart: 0,
        yEnd: 400,
        width: 6.8,
        leftEdgeOffset: 3.4,
        rightEdgeOffset: 3.4,
        hasCenterLine: false,
        laneConfidence: 0.05,
        surfaceCondition: 'PATCHWORK',
      },
    ],
  },

  SUDDEN_CROSSING: {
    id: 'SUDDEN_CROSSING',
    name: 'Sudden Animal / Pedestrian Crossing (Hero Demo)',
    tagline: 'Autonomous response to sudden stray cattle/pedestrian entering forward path',
    description:
      'Flagship demonstration: Ego cruises at 45 km/h. At 2.5s, an animal suddenly steps directly into the vehicle corridor. Watch the complete real-time chain: Perception → Prediction → Risk Spike → Path Rejection → Evasive Maneuver → Avoidance → Recovery.',
    difficulty: 'EXTREME',
    defaultSpeedKmh: 45,
    roadWidth: 7.2,
    laneConfidence: 0.4,
    expectedBehavior:
      'Cruise normally → Detect sudden crossing animal → Project expanding uncertainty envelope → Trigger high risk → Reject blocked center path → Select safe left evasive path or emergency brake → Clear hazard → Recover to cruise.',
    seed: 505,
    heroDemoTriggerDelaySec: 1.8,
    initialActors: [
      {
        id: 'hero_crossing_animal',
        type: 'ANIMAL', // Stray cow / dog waiting on shoulder
        x: 4.8, // Waiting on right roadside shoulder before crossing
        y: 62.0, // Longitudinal position ahead giving realistic ~26m perception-reaction-braking distance
        speed: 2.2,
        vx: 0,
        vy: 0,
        heading: -Math.PI / 2, // Facing road interior
        acceleration: 0,
        width: 1.0,
        length: 2.1,
        behavior: 'CROSSING',
        uncertainty: 0.65,
        targetX: -4.2, // Crosses completely to the opposite shoulder
        isTriggered: false, // Triggers dynamically at delay or distance
        triggerDistance: 28.0,
      },
      {
        id: 'shoulder_pedestrian',
        type: 'PEDESTRIAN',
        x: -3.0,
        y: 160.0, // Farther down road to allow clear observation of obstacle avoidance and cruise recovery
        speed: 1.2,
        vx: 0,
        vy: 1.2,
        heading: 0,
        acceleration: 0,
        width: 0.6,
        length: 0.6,
        behavior: 'SLOW_MOVING',
        uncertainty: 0.3,
      },
    ],
    initialPotholes: [
      { id: 'hero_pothole', x: 2.2, y: 70.0, diameter: 1.0, depth: 8, severity: 'MODERATE' },
    ],
    roadSegments: [
      {
        yStart: 0,
        yEnd: 450,
        width: 7.2,
        leftEdgeOffset: 3.6,
        rightEdgeOffset: 3.6,
        hasCenterLine: true,
        laneConfidence: 0.4,
        surfaceCondition: 'DRY_ASPHALT',
      },
    ],
  },
};
